/** Static end-of-tournament prize board. Not derived from live FIFA sync. */
export const FINAL_RESULTS = {
  title: "World Cup 2026 Sweepstake",
  subtitle: "Results",
  provisional: true,
  banner: "Pending final confirmation",
  main: [
    {
      place: "1st",
      trophy: "gold",
      houseId: "Coppice",
      houseLabel: "Coppice",
      teamName: "Spain",
      fifaCode: "ESP",
      amount: "£120",
      reason: "Tournament winners — beat Argentina in the final",
    },
    {
      place: "2nd",
      trophy: "silver",
      houseId: "12",
      houseLabel: "House 12",
      teamName: "Argentina",
      fifaCode: "ARG",
      amount: "£48",
      reason: "Finalists — lost the final to Spain",
    },
    {
      place: "3rd",
      trophy: "bronze",
      houseId: "4",
      houseLabel: "House 4",
      teamName: "England",
      fifaCode: "ENG",
      amount: "£28.80",
      reason: "3rd-place play-off winners — beat France 6–4",
    },
    {
      place: "4th",
      trophy: "fourth",
      houseId: "21",
      houseLabel: "House 21",
      teamName: "France",
      fifaCode: "FRA",
      amount: "£19.20",
      reason: "3rd-place play-off losers — lost to England 4–6",
    },
  ],
  side: [
    {
      place: "Wooden spoon",
      trophy: "spoon",
      houseId: "1",
      houseLabel: "House 1",
      teamName: "Iraq",
      fifaCode: "IRQ",
      amount: "£12",
      reason:
        "Most goals conceded (12). Tied with England and Tunisia — England out on more matches played (8 vs 3); Iraq beats Tunisia on worse goal difference (−11 vs −10).",
      confirming: true,
    },
    {
      place: "Fair play",
      trophy: "fairplay",
      houseId: "4",
      houseLabel: "House 4",
      teamName: "Netherlands",
      fifaCode: "NED",
      amount: "£12",
      reason: "FIFA Fair Play Award — three yellow cards, no reds across the tournament.",
      confirming: true,
    },
  ],
};
